#!/usr/bin/env python3
"""sync_exercises.py

Bring hand-written exercise files back in line with their sheets after
the sheets' text has been edited.

Manual exercise files (see smd2exercises.find_manual_exercises_path())
are never regenerated by the build, on purpose: they hold hand-tuned
distractors. The downside is that once a sheet's sentence or
vocabulary row is corrected in the .md, its exercises keep showing
the old text. build.py warns about it; this script fixes it.

For every sheet with a manual exercises file:

- manual exercises whose (l1, l2) pairs are all still taught by the
  sheet are kept exactly as they are (hand-tuned distractors survive);
- when only ONE side of a pair was edited (e.g. just the Slovak
  translation of an unchanged French sentence) and the untouched side
  identifies a single current pair, the exercise is updated in place:
  the text of the edited side is replaced, and its fill-blank /
  word-order data is re-derived from the new text when possible, so
  the hand-tuned distractors of the other side are kept;
- exercises written the wrong way round (l1 and l2 swapped: l1 must
  be the native language, l2 the target language) are turned back
  the right way first, then checked like the others;
- other manual exercises about a pair the sheet no longer teaches
  are dropped;
- for every pair the sheet now teaches but that no kept manual
  exercise covers at all (typically: the corrected version of a
  dropped sentence), the automatically generated exercises for that
  pair are added, in the generator's usual order. For "match"
  exercises, a generated one is added when it contains such a pair
  and a manual "match" was dropped.

- "put the words in order" exercises whose parasite words (the extra
  sentence mixed into their tokens) are no longer one of the sheet's
  sentences get a current one: the edited version of the same
  sentence when it can be identified, otherwise the sheet sentence
  sharing the fewest words with the target.

Pairs that were deliberately left without any exercise in a manual
file are not touched: only pairs that are genuinely new to the file
get generated exercises.

Per-file control, with a top-level "sync" key in the exercises file:
- "full" (default): everything above;
- "no-add": fix and update, drop what can't be fixed, but never add
  generated exercises (a file kept short on purpose);
- "off": never touched, and never reported by build.py (free-form
  exercises, e.g. a closing "thank you" page). Files in "append"
  mode are never touched either: their exercises are extras.

Dry run by default (prints what would change); pass --apply to write.
Added exercises get automatic distractors -- worth a manual look
afterwards (the report lists them).

Usage:
    python3 src/sync_exercises.py --lang-dir langs/fr-sk [--apply] [--seed N]
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

import smd2exercises as sx
from smd2data import SheetNameError


def resolve_pair(pair: tuple[str, str], known: set[tuple[str, str]]) -> tuple[str, str] | None:
    """The current pair a stale pair most likely became, when only one
    of its sides changed: same l2 and a single candidate, else same l1
    and a single candidate. None when ambiguous or both sides changed."""
    l1, l2 = pair
    same_l2 = [p for p in known if p[1] == l2]
    if len(same_l2) == 1:
        return same_l2[0]
    same_l1 = [p for p in known if p[0] == l1]
    if len(same_l1) == 1:
        return same_l1[0]
    return None


def _retokenize_order(tokens: list[str], old_text: str, new_text: str) -> list[str] | None:
    """Swap the leading tokens that spell `old_text` (target sentence,
    possibly regrouped into multi-word chips) for the tokens of
    `new_text`, keeping the trailing parasite tokens."""
    acc = []
    for i, tok in enumerate(tokens):
        acc.append(tok)
        if " ".join(acc).split() == old_text.split():
            return sx.tokenize(new_text) + tokens[i + 1:]
    return None


def _reblank(ex: dict[str, Any], side: str, new_text: str) -> bool:
    """Point a fill-blank's `side` ("l1"/"l2") at `new_text`, keeping
    its missing word and distractors if that word is still there."""
    missing = ex.get(f"missing_{side}")
    tokens = sx.tokenize(new_text)
    hits = [i for i, t in enumerate(tokens) if sx.strip_punct(t) == missing]
    if not hits:
        return False
    old_idx = ex.get(f"blank_index_{side}")
    ex[f"blank_index_{side}"] = old_idx if old_idx in hits else hits[0]
    return True


def swap_sides(ex: dict[str, Any]) -> dict[str, Any]:
    """A copy of `ex` with every l1/l2 field swapped (l1 <-> l2,
    choices_l1 <-> choices_l2, tokens_..., missing_..., blank_index_...)."""
    new = {}
    for key, value in ex.items():
        if key in ("l1", "l2"):
            new["l2" if key == "l1" else "l1"] = value
        elif key.endswith("_l1"):
            new[key[:-3] + "_l2"] = value
        elif key.endswith("_l2"):
            new[key[:-3] + "_l1"] = value
        else:
            new[key] = value
    # Keep the generator's field order (id, type, l1, l2, ...) so the
    # file stays readable.
    order = ["id", "type", "l1", "l2", "missing_l1", "missing_l2", "blank_index_l1",
             "blank_index_l2", "choices_l1", "choices_l2", "tokens_l1", "tokens_l2"]
    ordered = {k: new[k] for k in order if k in new}
    ordered.update({k: v for k, v in new.items() if k not in ordered})
    return json.loads(json.dumps(ordered))


def is_inverted(ex: dict[str, Any], known: set[tuple[str, str]]) -> bool:
    """True when the exercise looks written the wrong way round: none of
    its pairs is known as is, but at least one is known (or one side
    is known) once l1 and l2 are swapped."""
    pairs = sx.exercise_pairs(ex)
    if any(p in known for p in pairs):
        return False
    l1s = {p[0] for p in known}
    l2s = {p[1] for p in known}
    return any((b, a) in known or b in l1s or a in l2s for a, b in pairs)


def update_in_place(ex: dict[str, Any], known: set[tuple[str, str]]) -> dict[str, Any] | None:
    """A copy of stale exercise `ex` pointed at the current version of
    its pair(s), or None when that can't be done safely. Exercises
    written the wrong way round are swapped back first."""
    if is_inverted(ex, known):
        if ex.get("type") == "listen":
            # Its choices are one-sided (native side only): once swapped
            # they would be in the wrong language. Not recoverable.
            return None
        ex = swap_sides(ex)
        if all(p in known for p in sx.exercise_pairs(ex)):
            return ex
    new = json.loads(json.dumps(ex))
    if ex.get("type") == "match":
        targets = [resolve_pair(p, known) for p in sx.exercise_pairs(ex)]
        if any(t is None for t in targets):
            return None
        new["l1"] = [t[0] for t in targets]
        new["l2"] = [t[1] for t in targets]
        return new

    old = sx.exercise_pairs(ex)[0]
    target = resolve_pair(old, known)
    if target is None:
        return None
    for side, i in (("l1", 0), ("l2", 1)):
        if old[i] == target[i]:
            continue
        new[side] = target[i]
        if ex.get("type") == "fill-blank" and not _reblank(new, side, target[i]):
            return None
        if ex.get("type") == "order":
            tokens = _retokenize_order(ex.get(f"tokens_{side}", []), old[i], target[i])
            if tokens is None:
                return None
            new[f"tokens_{side}"] = tokens
    return new


def _split_order_tokens(tokens: list[str], text: str) -> tuple[list[str], list[str]] | None:
    """Split an order exercise's tokens into (target tokens, parasite
    tokens): the leading tokens that spell `text` (possibly regrouped
    into multi-word chips), and whatever follows. None if the tokens
    don't start with `text`."""
    acc = []
    for i, tok in enumerate(tokens):
        acc.append(tok)
        if " ".join(acc).split() == text.split():
            return tokens[:i + 1], tokens[i + 1:]
    return None


def sentence_pairs(record: dict[str, Any]) -> set[tuple[str, str]]:
    """The sheet's audio-card sentences long enough to serve as an order
    exercise's parasite -- the same pool generate_order() draws from."""
    pairs = set()
    for s in record["sentences"]:
        l1, l2 = s["l1"].strip(), s["l2"].strip()
        if len(sx.tokenize(l1)) >= sx.MIN_TOKENS_FOR_BLANK and len(sx.tokenize(l2)) >= sx.MIN_TOKENS_FOR_BLANK:
            pairs.add((l1, l2))
    return pairs


def refresh_parasite(ex: dict[str, Any], pool: set[tuple[str, str]], rng: random.Random) -> dict[str, Any] | None:
    """A copy of order exercise `ex` whose parasite words (the extra
    sentence mixed into its tokens) are taken from the sheet's current
    text, or None when nothing needs to change.

    The parasite is kept when it is still one of the sheet's sentences;
    when only one of its sides was edited, it follows the edit (same
    rule as resolve_pair()); otherwise it is replaced by another
    sentence of the sheet, picked among those sharing the fewest words
    with the target -- a parasite that repeats the target's own words
    makes the exercise confusing rather than harder."""
    if ex.get("type") != "order":
        return None
    split1 = _split_order_tokens(ex.get("tokens_l1") or [], ex["l1"])
    split2 = _split_order_tokens(ex.get("tokens_l2") or [], ex["l2"])
    if split1 is None or split2 is None:
        return None
    parasite = (" ".join(split1[1]), " ".join(split2[1]))
    if not parasite[0] and not parasite[1]:
        return None  # target alone, on purpose
    if parasite in pool:
        return None
    target_pair = (ex["l1"], ex["l2"])
    candidates = sorted(p for p in pool if p != target_pair)
    replacement = resolve_pair(parasite, pool)
    if replacement is None or replacement == target_pair:
        if not candidates:
            return None
        target_words = {w.lower() for w in sx.tokenize(ex["l2"])}

        def overlap(pair: tuple[str, str]) -> int:
            return len(target_words & {w.lower() for w in sx.tokenize(pair[1])})

        fewest = min(overlap(p) for p in candidates)
        replacement = rng.choice([p for p in candidates if overlap(p) == fewest])
    new = json.loads(json.dumps(ex))
    new["tokens_l1"] = split1[0] + sx.tokenize(replacement[0])
    new["tokens_l2"] = split2[0] + sx.tokenize(replacement[1])
    return new


def refresh_parasites(record: dict[str, Any], exercises: list[dict[str, Any]], rng: random.Random) -> tuple[list[dict[str, Any]], list]:
    """Apply refresh_parasite() to every order exercise of a manual file
    (not "off", not "append"). Returns (new list, [(old, new), ...])."""
    if record.get("manual_mode") == "append" or record.get("manual_sync") == "off":
        return exercises, []
    pool = sentence_pairs(record)
    out, changed = [], []
    for ex in exercises:
        fixed = refresh_parasite(ex, pool, rng)
        if fixed is None:
            out.append(ex)
        else:
            out.append(fixed)
            changed.append((ex, fixed))
    return out, changed


def sync_record(record: dict[str, Any], generated: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list, list, list]:
    """Return (new exercise list, dropped, added, updated) for one
    sheet with a manual exercises file. `updated` holds (old, new)."""
    manual = record["manual_exercises"] or []
    stale_ids = {id(ex) for ex in sx.find_stale_manual_exercises(record)}
    if not stale_ids:
        return manual, [], [], []

    known = sx.current_pairs(record)
    kept, dropped, updated = [], [], []
    for ex in manual:
        if id(ex) not in stale_ids:
            kept.append(ex)
            continue
        fixed = update_in_place(ex, known)
        if fixed is None:
            dropped.append(ex)
        else:
            kept.append(fixed)
            updated.append((ex, fixed))

    covered = {pair for ex in kept for pair in sx.exercise_pairs(ex)}
    if not dropped or record.get("manual_sync") == "no-add":
        return kept, dropped, [], updated
    new_pairs = sx.current_pairs(record) - covered
    dropped_match = any(ex.get("type") == "match" for ex in dropped)

    kept_ids = {ex.get("id") for ex in kept}
    added = []
    for ex in generated:
        pairs = sx.exercise_pairs(ex)
        if ex.get("type") == "match":
            wanted = dropped_match and any(p in new_pairs for p in pairs)
        else:
            wanted = pairs[0] in new_pairs
        if wanted and ex.get("id") not in kept_ids:
            added.append(ex)
            kept_ids.add(ex.get("id"))
    return kept + added, dropped, added, updated


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync manual exercise files with their (edited) sheets.")
    parser.add_argument("--lang-dir", type=Path, required=True, help="Language directory, e.g. langs/fr-sk")
    parser.add_argument("--apply", action="store_true", help="Write the changes (default: dry run)")
    parser.add_argument("--seed", type=int, help="Random seed for the generated distractors")
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    with (args.lang_dir / "lang.json").open(encoding="utf-8") as f:
        lang_cfg = json.load(f)

    try:
        records = sx.load_corpus(args.lang_dir / "md", lang_cfg)
    except (SheetNameError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    # Generate as if no manual file existed, to have a candidate for
    # every pair of every sheet.
    auto_records = [dict(r, manual_exercises=None, manual_mode="replace") for r in records]
    generated = sx.build_exercises_for_corpus(auto_records)

    total_dropped = total_added = total_updated = total_parasites = changed_files = 0
    # Parasite replacements use their own generator, so that they don't
    # shift the generated distractors of a given --seed.
    rng = random.Random(args.seed)
    for record in records:
        if not record.get("manual_exercises") or not record.get("manual_path"):
            continue
        new_list, dropped, added, updated = sync_record(record, generated[record["id"]]["exercises"])
        new_list, reparasited = refresh_parasites(record, new_list, rng)
        if not dropped and not updated and not reparasited:
            continue
        changed_files += 1
        total_dropped += len(dropped)
        total_added += len(added)
        total_updated += len(updated)
        total_parasites += len(reparasited)
        path = Path(record["manual_path"])
        print(f"\n{path}: ~{len(updated)} updated / -{len(dropped)} / +{len(added)} / {len(reparasited)} parasite(s)")
        for old, new in updated:
            print(f"  ~ {old.get('type'):11} {old.get('id')}")
        for old, new in reparasited:
            print(f"  p {old.get('type'):11} {old.get('id')}")
        for ex in dropped:
            print(f"  - {ex.get('type'):11} {ex.get('id')}")
        for ex in added:
            print(f"  + {ex.get('type'):11} {ex.get('id')}")
        if args.apply:
            with path.open(encoding="utf-8") as f:
                data = json.load(f)
            data["exercises"] = new_list
            path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    verb = "Updated" if args.apply else "Would update"
    print(f"\n{verb} {changed_files} file(s): {total_updated} exercise(s) updated in place, "
          f"{total_dropped} stale exercise(s) dropped, {total_added} generated exercise(s) added, "
          f"{total_parasites} order parasite(s) refreshed.")
    if not args.apply and changed_files:
        print("Dry run -- pass --apply to write.")


if __name__ == "__main__":
    main()
